allowBuilds:
  '@firebase/util': true
  '@swc/core': true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@firebase/util"
  - "@swc/core"
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
overrides:
  lodash: 4.18.1
  postcss: 8.5.19
