import { createServiceClient } from "@/lib/supabase/service"
import { createNotification, broadcast } from "@/lib/notifications/engine"
import { generateId } from "@/lib/utils/id"
import type { AgentAction, IntelligenceFinding } from "./agents"
import type { WorkflowStep } from "@/lib/workflows/types"

const ACTIONS_TABLE = "intelligence_actions"

export async function executeIntelligenceAction(action: AgentAction, organizationId: string): Promise<boolean> {
  const db = createServiceClient()
  await db.from(ACTIONS_TABLE).update({
    status: "executing",
    executed_at: new Date().toISOString(),
  }).eq("id", action.id).eq("organization_id", organizationId)

  try {
    let success = false

    switch (action.type) {
      case "renew_certification":
        success = await scheduleRenewal(action, organizationId)
        break
      case "create_remediation_plan":
        success = await createTask(action, organizationId)
        break
      case "create_purchase_order":
        success = await createTask(action, organizationId)
        break
      case "schedule_maintenance":
        success = await createTask(action, organizationId)
        break
      case "send_recovery_email":
        success = await notifyStakeholders(action, organizationId)
        break
      case "assign_pipeline_owner":
        success = await createTask(action, organizationId)
        break
      case "investigate_anomaly":
        success = await createTask(action, organizationId)
        break
      case "notify_stakeholder":
        success = await notifyStakeholders(action, organizationId)
        break
      default:
        success = await createTask(action, organizationId)
    }

    await db.from(ACTIONS_TABLE).update({
      status: success ? "completed" : "failed",
      result: JSON.stringify({ success }),
    }).eq("id", action.id).eq("organization_id", organizationId)

    if (success) {
      await broadcast(organizationId, {
        type: "success",
        category: "intelligence_action",
        priority: "normal",
        title: `AI completed: ${action.type.replace(/_/g, " ")}`,
        body: `Action on ${action.targetModule} was executed successfully`,
        action_url: "/intelligence",
        source: "system",
      })
    }

    return success
  } catch (err) {
    await db.from(ACTIONS_TABLE).update({
      status: "failed",
      result: JSON.stringify({ error: String(err) }),
    }).eq("id", action.id).eq("organization_id", organizationId)
    return false
  }
}

async function scheduleRenewal(action: AgentAction, organizationId: string): Promise<boolean> {
  const db = createServiceClient()
  await db.from("tasks").insert({
    organization_id: organizationId,
    title: `Renew certificate: ${action.targetModule || action.config?.domain || 'unknown entity'}`,
    description: `Auto-generated by ${action.agentId}: ${JSON.stringify(action.config)}`,
    status: "open",
    priority: "high",
    due_date: new Date(Date.now() + 14 * 86400000).toISOString(),
    source: "intelligence",
  })
  return true
}

async function createTask(action: AgentAction, organizationId: string): Promise<boolean> {
  const db = createServiceClient()
  await db.from("tasks").insert({
    organization_id: organizationId,
    title: `${action.type.replace(/_/g, " ")}: ${action.targetModule || action.config?.domain || 'unknown entity'}`,
    description: `Auto-generated by ${action.agentId}`,
    status: "open",
    priority: "medium",
    source: "intelligence",
  })
  return true
}

async function notifyStakeholders(action: AgentAction, organizationId: string): Promise<boolean> {
  const db = createServiceClient()
  const { data: profiles } = await db
    .from("profiles")
    .select("id")
    .eq("organization_id", organizationId)
    .limit(5)

  if (profiles && profiles.length > 0) {
    await broadcast(
      organizationId,
      {
        type: "info",
        category: "intelligence_action",
        priority: "high",
        title: `Action: ${action.type.replace(/_/g, " ")}: ${action.targetEntity}`,
        body: `AI agent ${action.agentId} requires attention`,
        action_url: "/intelligence",
        source: "system",
      },
      profiles.map((p: { id: string }) => p.id),
    )
  }
  return true
}

export async function executeAllApprovedActions(organizationId: string): Promise<number> {
  const db = createServiceClient()
  const { data: approved } = await db
    .from(ACTIONS_TABLE)
    .select("*")
    .eq("organization_id", organizationId)
    .eq("status", "approved")

  let count = 0
  for (const action of (approved || []) as Array<Record<string, unknown>>) {
    const agentAction: AgentAction = {
      id: action.id as string,
      agentId: action.agent_id as string,
      type: action.type as string,
      targetEntity: action.target_entity as string,
      targetModule: action.target_module as string,
      config: action.config as Record<string, unknown>,
      status: "approved",
      confidence: action.confidence as number,
      requiresApproval: action.requires_approval as boolean,
    }
      const ok = await executeIntelligenceAction(agentAction, organizationId)
    if (ok) count++
  }
  return count
}
